site_name: HashVer
theme:
  name: material
  palette:
    primary: deep orange
    accent: light blue

repo_name: miniscruff/hashver
repo_url: https://github.com/miniscruff/hashver
markdown_extensions:
  - admonition
  - footnotes
